version: "3.7"

services:
  api:
    image: homemate-api-dev
    container_name: 'homemate-api'
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - .:/app/
      - /app/node_modules
      - /app/logs
    networks: 
      - backend
    depends_on: 
      - db
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
      BASE_URL: localhost
      DB_DIALECT: postgres
      DB_PORT: 5432
      DB_HOST: db
      DB_NAME: Homemate
      DB_USERNAME: postgres
      DB_PASSWORD: root_winx
    command: ./wait-for.sh db:5432 -- npm run start

  db:
    image: postgres:9.6
    container_name: 'homemate-db'
    restart: unless-stopped
    volumes:
      - ./config/database/init.sql:/data/application/init.sql
      - local_db_data:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: root_winx
      POSTGRES_DB: Homemate
    ports:
      - "5432:5432"
    networks: 
      - backend

volumes:
  local_db_data: {}
  node_modules:
  
networks:
  backend:
    driver: 'bridge'
  