const swaggerAutogen = require('swagger-autogen')();
const { API_PORT } = require('../config/environment');

const outputFile = './swagger_output.json';
const endpointsFiles = ['../routes.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'HOMEMATE API',
    description:
      'Documentation automatically generated by the <b>swagger.autogen</b> module.',
  },
  host: `localhost:${API_PORT}`,
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [],
  securityDefinitions: {},
  definitions: {},
};

swaggerAutogen(outputFile, endpointsFiles, doc);
