const OK_STATUS = 200
const CREATED = 201
const ACCEPTED = 202
const NO_CONTENT = 204
const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const NOT_FOUND = 404
const METHOD_NOT_ALLOWED = 405
const INTERNAL_SERVER_ERROR = 500

module.exports = {
    OK_STATUS,
    NOT_FOUND,
    BAD_REQUEST,
    UNAUTHORIZED,
    CREATED,
    NO_CONTENT,
    Internal_Server_Error: INTERNAL_SERVER_ERROR,
    ACCEPTED,
    METHOD_NOT_ALLOWED
}
